import { CamRecommendation } from "@/lib/cams/types";
import { familyTokensForSearch } from "@/lib/cams/utils";

export type GlobalCamCatalogEntry = CamRecommendation & { familyTags: string[] };

const RAW_CATALOG: Array<Omit<GlobalCamCatalogEntry, "familyTags"> & { familyTags?: string[] }> = [
  {
    id: "gm-ls3-tsp-stage2",
    make: "Chevy / GM",
    family: "Gen III/IV LS (4.8/5.3/5.7/6.0/6.2/7.0)",
    brand: "Texas Speed & Performance",
    pn: "25-TSPSTG2-LS3",
    name: "Stage 2 LS3 N/A",
    durInt: 229,
    durExh: 244,
    lsa: 112,
    liftInt: 0.629,
    liftExh: 0.615,
    peakHpRpm: 6600,
    boostOK: "no",
    notes: "Popular NA street/strip grind for cathedral-port LS3 conversions.",
    sourceUrl: "https://www.texas-speed.com/p-4029-texas-speed-stage-2-ls3-na-camshaft.aspx",
  },
  {
    id: "gm-ls3-btr-stage3",
    make: "Chevy / GM",
    family: "Gen III/IV LS (4.8/5.3/5.7/6.0/6.2/7.0)",
    brand: "Brian Tooley Racing",
    pn: "BTR-LS3-STG3",
    name: "Stage 3 LS3",
    durInt: 233,
    durExh: 248,
    lsa: 113,
    liftInt: 0.636,
    liftExh: 0.636,
    peakHpRpm: 6800,
    boostOK: "either",
    notes: "Aggressive cathedral-port spec for high-RPM LS3 combos.",
    sourceUrl: "https://briantooleyracing.com/ls3-stage-3-camshaft-kit.html",
  },
  {
    id: "gm-ls-truck-btr-norris",
    make: "Chevy / GM",
    family: "Gen III/IV LS (4.8/5.3/5.7/6.0/6.2/7.0)",
    brand: "Brian Tooley Racing",
    pn: "BTR31824110",
    name: "Truck Norris",
    durInt: 212,
    durExh: 226,
    lsa: 107,
    liftInt: 0.552,
    liftExh: 0.552,
    peakHpRpm: 6100,
    boostOK: "no",
    notes: "Torque-focused cam for 4.8-6.2L truck applications.",
    sourceUrl: "https://briantooleyracing.com/truck-norris-camshaft.html",
  },
  {
    id: "gm-ls-btr-turbo-truck",
    make: "Chevy / GM",
    family: "Gen III/IV LS (4.8/5.3/5.7/6.0/6.2/7.0)",
    brand: "Brian Tooley Racing",
    pn: "BTR-TT-227",
    name: "Twin Turbo Truck",
    durInt: 227,
    durExh: 235,
    lsa: 115,
    liftInt: 0.618,
    liftExh: 0.618,
    peakHpRpm: 6400,
    boostOK: "yes",
    notes: "Designed for boosted 4.8-6.2L truck builds.",
    sourceUrl: "https://briantooleyracing.com/gen-iii-iv-ls-twin-turbo-truck-camshaft.html",
  },
  {
    id: "gm-lt-btr-stage2",
    make: "Chevy / GM",
    family: "Gen V LT (LT1/LT2/LT4/LT5)",
    brand: "Brian Tooley Racing",
    pn: "BTR-LT1-STG2",
    name: "Stage 2 LT1",
    durInt: 223,
    durExh: 238,
    lsa: 116,
    liftInt: 0.636,
    liftExh: 0.636,
    peakHpRpm: 6400,
    boostOK: "either",
    notes: "LT1/LT4 grind that supports DI heads + mild boost.",
    sourceUrl: "https://briantooleyracing.com/lt1-stage-2-camshaft-kit.html",
  },
  {
    id: "gm-lt-comp-477",
    make: "Chevy / GM",
    family: "Gen V LT (LT1/LT2/LT4/LT5)",
    brand: "COMP Cams",
    pn: "54-477-11",
    name: "NSR LT1",
    durInt: 227,
    durExh: 235,
    lsa: 115,
    liftInt: 0.621,
    liftExh: 0.624,
    peakHpRpm: 6500,
    boostOK: "either",
    notes: "LT1/LT4-friendly grind listed at Summit Racing.",
    sourceUrl: "https://www.summitracing.com/parts/cca-54-477-11",
  },
  {
    id: "gm-ls-comp-xr275",
    make: "Chevy / GM",
    family: "Gen III/IV LS (4.8/5.3/5.7/6.0/6.2/7.0)",
    brand: "COMP Cams",
    pn: "54-469-11",
    name: "XR275HR",
    durInt: 222,
    durExh: 224,
    lsa: 112,
    liftInt: 0.566,
    liftExh: 0.568,
    peakHpRpm: 6100,
    boostOK: "either",
    notes: "Popular XR275HR cam sold via Summit Racing.",
    sourceUrl: "https://www.summitracing.com/parts/cca-54-469-11",
  },
  {
    id: "ford-coyote-fp-stage3",
    make: "Ford",
    family: "Coyote / Modular DOHC (5.0 Coyote)",
    brand: "Ford Performance",
    pn: "M-6550-M50B",
    name: "Coyote Stage 3",
    durInt: 236,
    durExh: 240,
    lsa: 110,
    liftInt: 0.529,
    liftExh: 0.542,
    peakHpRpm: 7800,
    boostOK: "no",
    notes: "Track Pack cam set from Ford Performance for 2015+ 5.0L.",
    sourceUrl: "https://performanceparts.ford.com/part/M-6550-M50B",
  },
  {
    id: "ford-coyote-comp-stage2",
    make: "Ford",
    family: "Coyote / Modular DOHC (5.0 Coyote)",
    brand: "COMP Cams",
    pn: "106-462-11",
    name: "NSR Stage 2",
    durInt: 231,
    durExh: 235,
    lsa: 126,
    liftInt: 0.472,
    liftExh: 0.453,
    peakHpRpm: 7500,
    boostOK: "either",
    notes: "No-springs-required grind for Gen 2/3 Coyotes.",
    sourceUrl: "https://www.compcams.com/coyote-nsr-stage-2-camshafts.html",
  },
  {
    id: "ford-coyote-afm-n51",
    make: "Ford",
    family: "Coyote / Modular DOHC (5.0 Coyote)",
    brand: "Anderson Ford Motorsport",
    pn: "AFM-N51",
    name: "N-51 NA",
    durInt: 234,
    durExh: 238,
    lsa: 112,
    liftInt: 0.550,
    liftExh: 0.530,
    peakHpRpm: 7800,
    boostOK: "no",
    notes: "Aggressive Anderson grind for high-compression Coyotes.",
    sourceUrl: "https://www.andersonfordmotorsport.com/products/n-51-na-camshafts",
  },
  {
    id: "ford-coyote-afm-nsr",
    make: "Ford",
    family: "Coyote / Modular DOHC (5.0 Coyote)",
    brand: "Anderson Ford Motorsport",
    pn: "AFM-NSR-121200",
    name: "NSR 121200",
    durInt: 224,
    durExh: 228,
    lsa: 125,
    liftInt: 0.490,
    liftExh: 0.485,
    peakHpRpm: 7200,
    boostOK: "either",
    notes: "Drop-in no-springs-required set for street Coyotes.",
    sourceUrl: "https://www.andersonfordmotorsport.com/products/2011-2023-coyote-nsr-camshafts",
  },
  {
    id: "ford-coyote-bullet",
    make: "Ford",
    family: "Coyote / Modular DOHC (5.0 Coyote)",
    brand: "Bullet Race Engineering",
    pn: "BRE-COY-290",
    name: "290 Street/Strip",
    durInt: 242,
    durExh: 246,
    lsa: 113,
    liftInt: 0.520,
    liftExh: 0.510,
    peakHpRpm: 8200,
    boostOK: "no",
    notes: "Aggressive street/strip cam for ported-head Coyotes.",
    sourceUrl: "https://www.bulletcams.com/custom-grinds-modular/",
  },
  {
    id: "ford-windsor-trickflow-trackmax",
    make: "Ford",
    family: "SBF Windsor (221/260/289/302/351W)",
    brand: "Trick Flow Specialties",
    pn: "TFS-51403001",
    name: "Track Max Stage 2",
    durInt: 228,
    durExh: 232,
    lsa: 110,
    liftInt: 0.542,
    liftExh: 0.563,
    peakHpRpm: 6500,
    boostOK: "no",
    notes: "Hyd roller for 5.0/5.8L Windsor street combos.",
    sourceUrl: "https://www.trickflow.com/parts/tfs-51403001",
  },
  {
    id: "ford-windsor-afm-b41",
    make: "Ford",
    family: "SBF Windsor (221/260/289/302/351W)",
    brand: "Anderson Ford Motorsport",
    pn: "AFM-B41",
    name: "B-41 N/A",
    durInt: 234,
    durExh: 244,
    lsa: 110,
    liftInt: 0.560,
    liftExh: 0.570,
    peakHpRpm: 6600,
    boostOK: "no",
    notes: "Classic AFM B-series cam for 5.0 street/strip cars.",
    sourceUrl: "https://www.andersonfordmotorsport.com/products/b-41-camshaft-kit",
  },
  {
    id: "ford-godzilla-btr-stage1",
    make: "Ford",
    family: "Godzilla (7.3)",
    brand: "Brian Tooley Racing",
    pn: "BTR-GDZ-ST1",
    name: "Stage 1 Godzilla",
    durInt: 218,
    durExh: 224,
    lsa: 115,
    liftInt: 0.612,
    liftExh: 0.598,
    peakHpRpm: 6000,
    boostOK: "either",
    notes: "Drop-in cam for the 7.3L modern pushrod platform.",
    sourceUrl: "https://briantooleyracing.com/7-3l-godzilla-stage-1-camshaft.html",
  },
  {
    id: "mopar-gen3hemi-comp-hrt2",
    make: "Mopar",
    family: "Gen III Hemi (5.7/6.1/6.2/6.4)",
    brand: "COMP Cams",
    pn: "68-300-5",
    name: "HRT Stage 2",
    durInt: 222,
    durExh: 230,
    lsa: 115,
    liftInt: 0.619,
    liftExh: 0.612,
    peakHpRpm: 6400,
    boostOK: "either",
    notes: "New HRT lobe series for Gen III Hemi street cars.",
    sourceUrl: "https://www.compcams.com/hrt-camshafts-for-gen-iii-hemi.html",
  },
  {
    id: "mopar-gen3hemi-btr-stage2",
    make: "Mopar",
    family: "Gen III Hemi (5.7/6.1/6.2/6.4)",
    brand: "Brian Tooley Racing",
    pn: "BTR-HEMI-STG2",
    name: "Stage 2 Hemi",
    durInt: 226,
    durExh: 234,
    lsa: 115,
    liftInt: 0.616,
    liftExh: 0.604,
    peakHpRpm: 6600,
    boostOK: "either",
    notes: "Hemi street/strip grind that supports boost.",
    sourceUrl: "https://briantooleyracing.com/gen-iii-hemi-stage-2-camshaft.html",
  },
  {
    id: "mopar-brb-lunati-voodoo",
    make: "Mopar",
    family: "B/RB Big Block (361/383/400/413/426W/440)",
    brand: "Lunati",
    pn: "10230702",
    name: "Voodoo 702",
    durInt: 226,
    durExh: 234,
    lsa: 110,
    liftInt: 0.494,
    liftExh: 0.513,
    peakHpRpm: 6000,
    boostOK: "no",
    notes: "Voodoo hydraulic flat tappet widely stocked at Summit.",
    sourceUrl: "https://www.summitracing.com/parts/lun-10230702",
  },
  {
    id: "mopar-la-hughes-whiplash",
    make: "Mopar",
    family: "LA Small Block (273/318/340/360)",
    brand: "Hughes Engines",
    pn: "SER0814BL-14",
    name: "Whiplash",
    durInt: 226,
    durExh: 230,
    lsa: 110,
    liftInt: 0.525,
    liftExh: 0.536,
    peakHpRpm: 5800,
    boostOK: "no",
    notes: "Choppy idle small-block Mopar cam with hyd rollers.",
    sourceUrl: "https://www.hughesengines.com/Index/products.php?partid=25702",
  },
  {
    id: "mopar-la-comp-thumpr",
    make: "Mopar",
    family: "LA Small Block (273/318/340/360)",
    brand: "COMP Cams",
    pn: "20-601-4",
    name: "Thumpr 287",
    durInt: 235,
    durExh: 249,
    lsa: 107,
    liftInt: 0.498,
    liftExh: 0.486,
    peakHpRpm: 6000,
    boostOK: "no",
    notes: "Choppy idle LA cam for street cars.",
    sourceUrl: "https://www.compcams.com/thumpr-cam-and-lifter-kit-for-chrysler-273-360.html",
  },
  {
    id: "mopar-brb-comp-xe274",
    make: "Mopar",
    family: "B/RB Big Block (361/383/400/413/426W/440)",
    brand: "COMP Cams",
    pn: "21-670-4",
    name: "XE274H-10",
    durInt: 230,
    durExh: 236,
    lsa: 110,
    liftInt: 0.488,
    liftExh: 0.491,
    peakHpRpm: 6000,
    boostOK: "no",
    notes: "XE hydraulic flat tappet for B/RB muscle cars.",
    sourceUrl: "https://www.compcams.com/x-treme-energy-camshafts-big-block-mopar.html",
  },
  {
    id: "toyota-jz-hks-264",
    make: "Toyota / Lexus",
    family: "JZ (1JZ/2JZ)",
    brand: "HKS",
    pn: "2202-RN025",
    name: "Step 2 264°",
    durInt: 264,
    durExh: 264,
    lsa: 110,
    liftInt: 0.402,
    liftExh: 0.402,
    peakHpRpm: 7800,
    boostOK: "yes",
    notes: "Drop-in pair for 2JZ-GTE street/strip turbo builds.",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cam/index.php?no=2202-rn025",
  },
  {
    id: "toyota-uz-toda-264",
    make: "Toyota / Lexus",
    family: "UZ (1UZ/3UZ)",
    brand: "TODA Racing",
    pn: "14111-UZ1-041",
    name: "High Power 264",
    durInt: 264,
    durExh: 264,
    lsa: 112,
    liftInt: 0.394,
    liftExh: 0.394,
    peakHpRpm: 7200,
    boostOK: "either",
    notes: "264° profile tailored for 1UZ/3UZ NA builds.",
    sourceUrl: "https://www.toda-racing.co.jp/en/product/camshaft/uz.html",
  },
  {
    id: "toyota-gr-kelford-248",
    make: "Toyota / Lexus",
    family: "GR (2GR/3GR/4GR)",
    brand: "Kelford Cams",
    pn: "248-E",
    name: "2GR-FE Street",
    durInt: 272,
    durExh: 272,
    lsa: 112,
    liftInt: 0.382,
    liftExh: 0.382,
    peakHpRpm: 7000,
    boostOK: "either",
    notes: "Street-friendly grind for 2GR-FE swap platforms.",
    sourceUrl: "https://www.kelfordcams.com/products/2gr-fe-performance-camshafts",
  },
  {
    id: "nissan-rb-tomei-260",
    make: "Nissan / Infiniti",
    family: "RB (RB20/25/26)",
    brand: "Tomei Powered",
    pn: "143044",
    name: "Poncams Type B 260",
    durInt: 260,
    durExh: 260,
    lsa: 110,
    liftInt: 0.404,
    liftExh: 0.404,
    peakHpRpm: 7800,
    boostOK: "yes",
    notes: "Drop-in cams for RB25/RB26 with upgraded turbos.",
    sourceUrl: "https://www.tomeiusa.com/poncams-rb26dett/",
  },
  {
    id: "nissan-vq-jwt-c8",
    make: "Nissan / Infiniti",
    family: "VQ (VQ35/VQ37)",
    brand: "Jim Wolf Technology",
    pn: "JWT-VQ-C8",
    name: "VQ37 C8",
    durInt: 272,
    durExh: 276,
    lsa: 112,
    liftInt: 0.480,
    liftExh: 0.465,
    peakHpRpm: 7600,
    boostOK: "either",
    notes: "Aggressive NA spec for 370Z/G37 road race builds.",
    sourceUrl: "https://jimwolftechnology.com/wolfpdf/C8-CAMINFO.pdf",
  },
  {
    id: "nissan-vr-tomei-procam",
    make: "Nissan / Infiniti",
    family: "VR (VR30/VR38)",
    brand: "Tomei Powered",
    pn: "143202",
    name: "Procam 272",
    durInt: 272,
    durExh: 272,
    lsa: 114,
    liftInt: 0.433,
    liftExh: 0.433,
    peakHpRpm: 8000,
    boostOK: "yes",
    notes: "GT-R oriented set for big turbo VR38 builds.",
    sourceUrl: "https://www.tomeiusa.com/procam-vr38dett/",
  },
  {
    id: "honda-k20-skunk2-pro3",
    make: "Honda / Acura",
    family: "K-Series (K20/K24)",
    brand: "Skunk2 Racing",
    pn: "305-05-7000",
    name: "Pro 3",
    durInt: 249,
    durExh: 249,
    lsa: 108,
    liftInt: 0.525,
    liftExh: 0.521,
    peakHpRpm: 8800,
    boostOK: "no",
    notes: "High-lift NA grind for 30-35 psi of spring pressure.",
    sourceUrl: "https://skunk2.com/products/305-05-7000",
  },
  {
    id: "honda-k24-dragcartel-32",
    make: "Honda / Acura",
    family: "K-Series (K20/K24)",
    brand: "Drag Cartel",
    pn: "DC-32",
    name: "3.2 All Motor",
    durInt: 252,
    durExh: 252,
    lsa: 110,
    liftInt: 0.550,
    liftExh: 0.540,
    peakHpRpm: 9000,
    boostOK: "no",
    notes: "Well-known K24/K20 swap cam for all-motor setups.",
    sourceUrl: "https://dragcartel.com/product/drag-cartel-3-2-camshaft/",
  },
  {
    id: "honda-b18-toda-specb",
    make: "Honda / Acura",
    family: "B-Series (B16/B18)",
    brand: "TODA Racing",
    pn: "14111-B16-020",
    name: "Spec B",
    durInt: 255,
    durExh: 253,
    lsa: 110,
    liftInt: 0.488,
    liftExh: 0.472,
    peakHpRpm: 8600,
    boostOK: "no",
    notes: "Spec B cams for high-compression B-series builds.",
    sourceUrl: "https://www.toda-racing.co.jp/en/product/camshaft/b16a.html",
  },
  {
    id: "subaru-ej25-kelford-272",
    make: "Subaru",
    family: "EJ (EJ20/EJ25)",
    brand: "Kelford Cams",
    pn: "199-G",
    name: "272/272",
    durInt: 272,
    durExh: 272,
    lsa: 112,
    liftInt: 0.421,
    liftExh: 0.421,
    peakHpRpm: 7600,
    boostOK: "yes",
    notes: "Popular 272 set for EJ25 big turbo cars.",
    sourceUrl: "https://www.kelfordcams.com/products/ej25-performance-camshafts",
  },
  {
    id: "subaru-fa20-gsc-s1",
    make: "Subaru",
    family: "FA/FB (FA20/FA24/FB20/FB25)",
    brand: "GSC Power Division",
    pn: "7026S1",
    name: "Stage 1",
    durInt: 260,
    durExh: 260,
    lsa: 112,
    liftInt: 0.413,
    liftExh: 0.413,
    peakHpRpm: 7400,
    boostOK: "either",
    notes: "FA20 Turbo/DIT upgrade cam that keeps AVCS happy.",
    sourceUrl: "https://www.gscpowderdivision.com/7026s1",
  },
  {
    id: "subaru-fa24-kelford-264",
    make: "Subaru",
    family: "FA/FB (FA20/FA24/FB20/FB25)",
    brand: "Kelford Cams",
    pn: "205-E",
    name: "264 Street",
    durInt: 264,
    durExh: 264,
    lsa: 112,
    liftInt: 0.402,
    liftExh: 0.402,
    peakHpRpm: 7200,
    boostOK: "either",
    notes: "FA24/FA20DIT-friendly grind for street boost.",
    sourceUrl: "https://www.kelfordcams.com/products/fa20-dit-performance-camshafts",
  },
  {
    id: "vw-ea888-ie-stage1",
    make: "VW / Audi",
    family: "EA888 (1.8T/2.0T Gen 1-4)",
    brand: "Integrated Engineering",
    pn: "IE-EA888-STG1",
    name: "Stage 1",
    durInt: 252,
    durExh: 252,
    lsa: 112,
    liftInt: 0.402,
    liftExh: 0.402,
    peakHpRpm: 6800,
    boostOK: "yes",
    notes: "Shelf cam set for Gen 3 MQB cars with stock heads.",
    sourceUrl: "https://performancebyie.com/products/ie-ea888-e-audi-vw-2-0t-camshafts",
  },
  {
    id: "vw-ea888-apr-stage2",
    make: "VW / Audi",
    family: "EA888 (1.8T/2.0T Gen 1-4)",
    brand: "APR",
    pn: "MS100187",
    name: "Stage 2",
    durInt: 260,
    durExh: 260,
    lsa: 110,
    liftInt: 0.409,
    liftExh: 0.409,
    peakHpRpm: 7100,
    boostOK: "yes",
    notes: "APR Motorsport grind for high-flow Gen 3 setups.",
    sourceUrl: "https://www.goapr.com/products/apr-ea888-gen-3-camshafts/",
  },
  {
    id: "vw-vr6-schimmel-sp263",
    make: "VW / Audi",
    family: "VR6 (2.8/3.2/3.6)",
    brand: "Schimmel Performance",
    pn: "SP263",
    name: "SP263",
    durInt: 263,
    durExh: 263,
    lsa: 110,
    liftInt: 0.433,
    liftExh: 0.433,
    peakHpRpm: 7200,
    boostOK: "either",
    notes: "Alloy VR6 street/strip cam with aggressive ramps.",
    sourceUrl: "https://shop.schimmelperformance.com/products/sp263-camshafts",
  },
  {
    id: "bmw-n54-schrick-264",
    make: "BMW",
    family: "N54/N55",
    brand: "Schrick",
    pn: "0437E0581",
    name: "264/248",
    durInt: 264,
    durExh: 248,
    lsa: 112,
    liftInt: 0.402,
    liftExh: 0.390,
    peakHpRpm: 7200,
    boostOK: "yes",
    notes: "Schrick billet cams for turbo N54/N55 builds.",
    sourceUrl: "https://www.schrick.com/en/products/camshafts",
  },
  {
    id: "bmw-b58-catcams-2804103",
    make: "BMW",
    family: "B58",
    brand: "Cat Cams",
    pn: "2804103",
    name: "Stage 2",
    durInt: 272,
    durExh: 264,
    lsa: 114,
    liftInt: 0.386,
    liftExh: 0.386,
    peakHpRpm: 7500,
    boostOK: "yes",
    notes: "Cat Cams profile for high-boost B58 applications.",
    sourceUrl: "https://www.catcams.com/products/camshafts",
  },
  {
    id: "bmw-s58-vac-stage2",
    make: "BMW",
    family: "S58",
    brand: "VAC Motorsports",
    pn: "VAC-S58-STG2",
    name: "Stage 2",
    durInt: 280,
    durExh: 272,
    lsa: 114,
    liftInt: 0.430,
    liftExh: 0.418,
    peakHpRpm: 7800,
    boostOK: "yes",
    notes: "VAC billet cam upgrade for G8X/G87 platforms.",
    sourceUrl: "https://www.vacmotorsports.com/",
  },
];

export const GLOBAL_CAM_CATALOG: GlobalCamCatalogEntry[] = RAW_CATALOG.map((entry) => ({
  ...entry,
  familyTags: entry.familyTags && entry.familyTags.length > 0 ? entry.familyTags : familyTokensForSearch(entry.family),
}));
